(defun totalpages (/ total)
  (setq total 0)
  (foreach page (layoutlist)
	   (cond ((or (equal "CVR" page)
		      (equal "FP" page)
		      (equal "BL" page)))
		 (t (setq total (+ 1 total)))))
  total))
